### ISSUE TITLE
Same json are not validate

### ISSUE THREAD

**Issue by beastie87** [savchukidze/lutsk_rada4you#1]
Андрію привіт!
Зверни будь ласка увагу на  ["2018-08-29", "2018-11-29", "2018-12-21", "2019-01-30", "2019-04-24", "2019-08-21", "2019-08-28"] ці датасети
вони мають ось таку проблему  `JSON::ParserError: 409: unexpected token at ', { "result": "absent", "voter_id": "1111" }, `
ось що в коді `, { "votes": [, { "result": "absent", "voter_id": "1111" }, `
кома `[, {` зайва, може якісь дані загубились, а може вона просо зайва, перевір будь ласка!
Дякую!

**Comment by savchukidze** [comment]
У цих файлах були питання порядку денного за які не проводились голосування.
Видалив їх із json файлів, в README додав уточнення. 
Пробуй тепер.

**Comment by beastie87** [comment]
Дякую, тепер все ОК, сайт оновив
